### ISSUE TITLE
Python 3 support ?

### ISSUE THREAD

**Issue by GMLudo** [acsone/pycoda#8]
Hi,

Thanks for this library, it works pretty well.
However, we need to use it in a Python 3 environment.

We did a quick'n'dirty fork for that: https://github.com/Eyepea/pycoda
Are you interested in by a cleaner version for a pull request ?

Have a nice day.

**Comment by sbidoul** [comment]
Hi Ludovic,

Sure we are. It should be possible to have the code compatible with python 2 and 3, so we'll definitely review a PR for that.

-sbi

**Comment by GMLudo** [comment]
Hi @sbidoul,

Ok, we will do that when we will have few time and adapt **travis.yml** to test also with Python 3.
Certainly we will use **six** to keep Python 2 compatibility.

Have a nice week.

**Comment by sbidoul** [comment]
This is now resolved.
